galaxy_info:
  author: Eric Kleinsorgen
  description: Update CatalogSource polling
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibmce
    - ansible
    - ocp
    - catalog_source

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
